# Generated by Django 4.1.4 on 2022-12-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pubsbars',
            options={'ordering': ['id']},
        ),
    ]
