# Generated by Django 4.1.4 on 2023-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs_app', '0002_alter_pubsbars_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsbars',
            name='foosball',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pubsbars',
            name='outside_tables',
            field=models.BooleanField(null=True),
        ),
    ]
